#include<stdio.h>
void main()
{
    int month_number;
    printf("enter month number:");
    scanf("%d",&month_number);

    if(month_number==1)
    {
        printf("january");
    }
    if(month_number==2)
    {
        printf("fabruary");
    }
    if(month_number==3)
    {
        printf("march");
    }
    if(month_number==4)
    {
        printf("april");
    }
    if|(month_number==5)
    {
        printf("may");
    }
    if(month_number==6)
    {
        printf("june");
    }
    if(month_number==7)
    {
        printf("july");
    }
    if(month_numbe==8)
    {
        printf("augest");
    }
    if(month_numbe==9)
    {
        printf("sepptember");
    }
    if(month_numbe==10)
    {
        printf("october");
    }
     if(month_numbe==11)
    {
        printf("november");
    }
     if(month_numbe==12)
    {
        printf("december");
    }
     if(month_numbe>12)
    {
        printf("invalid number");
    }
}